### ISSUE TITLE
Task 1 --

### ISSUE THREAD

**Issue by effervescence18** [iteloo/bitesize-berlin#11]
Find: Old photos of the Garden Sansoucci and the Palace  

Purpose: For the picture to hold in front of the Palace and Garden

**Comment by nini92828** [comment]
https://www.cntraveler.com/story/why-a-visit-to-berlin-should-include-a-day-trip-to-potsdam
http://www.wikiwand.com/en/Georg_Wenzeslaus_von_Knobelsdorff
https://www.google.com.tw/imgres?imgurl=https%3A%2F%2Fi.pinimg.com%2Foriginals%2Fb4%2Fc2%2F22%2Fb4c222ef1c518959ec3a55b5d1174972.jpg&imgrefurl=https%3A%2F%2Fwww.pinterest.com%2Fpin%2F382102349615584713%2F&docid=191OhYTpIF487M&tbnid=uNOmYX2zkSDzIM%3A&vet=10ahUKEwi0k6_vv_zZAhWKvLwKHRYdCgIQMwhEKAcwBw..i&w=600&h=439&itg=1&safe=strict&bih=803&biw=1440&q=Gardens%20Sanssouci%20berlin%20painting&ved=0ahUKEwi0k6_vv_zZAhWKvLwKHRYdCgIQMwhEKAcwBw&iact=mrc&uact=
https://www.google.com.tw/imgres?imgurl=https%3A%2F%2Fimages.fineartamerica.com%2Fimages-medium-large-5%2Fin-the-gardens-of-sanssouci-kiril-stanchev.jpg&imgrefurl=https%3A%2F%2Ffineartamerica.com%2Ffeatured%2Fin-the-gardens-of-sanssouci-kiril-stanchev.html&docid=z6xMvaczYlVHdM&tbnid=Nm8wljB7-DDPsM%3A&vet=10ahUKEwi0k6_vv_zZAhWKvLwKHRYdCgIQMwhCKAUwBQ..i&w=900&h=760&itg=1&safe=strict&bih=803&biw=1440&q=Gardens%20Sanssouci%20berlin%20painting&ved=0ahUKEwi0k6_vv_zZAhWKvLwKHRYdCgIQMwhCKAUwBQ&iact=mrc&uact=88


Old Picture

**Comment by nini92828** [comment]
https://www.google.com.tw/imgres?imgurl=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fthumb%2Fc%2Fc1%2FP1190390_Potsdam_sans_souci_rwk.jpg%2F1200px-P1190390_Potsdam_sans_souci_rwk.jpg&imgrefurl=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FPalaces_and_Parks_of_Potsdam_and_Berlin&docid=EoE9WmxhRUgH8M&tbnid=yGNeNq3aN1AN3M%3A&vet=10ahUKEwjitczBwPzZAhVCULwKHRcxAlUQMwg9KAAwAA..i&w=1200&h=823&safe=strict&bih=803&biw=702&q=Gardens%20Sanssouci%20berlin%20p&ved=0ahUKEwjitczBwPzZAhVCULwKHRcxAlUQMwg9KAAwAA&iact=mrc&uact=8
https://www.google.com.tw/imgres?imgurl=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fthumb%2Fb%2Fb1%2FChinesisches_Haus_Sanssouci.jpg%2F1200px-Chinesisches_Haus_Sanssouci.jpg&imgrefurl=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FChinese_House_(Potsdam)&docid=1UmqVxrlVzszwM&tbnid=KEI4kQePcbVn6M%3A&vet=10ahUKEwjitczBwPzZAhVCULwKHRcxAlUQMwhbKBQwFA..i&w=1200&h=1066&safe=strict&bih=803&biw=702&q=Gardens%20Sanssouci%20berlin%20p&ved=0ahUKEwjitczBwPzZAhVCULwKHRcxAlUQMwhbKBQwFA&iact=mrc&uact=8

New
