### ISSUE TITLE
Task 3 (Garden Sansoucci and Palace) --

### ISSUE THREAD

**Issue by effervescence18** [iteloo/bitesize-berlin#13]
Find and research interesting information about Fredrich the Great 

Purpose: Make the video fun and informative

**Comment by nini92828** [comment]
In 1730 Frederick and a young friend, Lieutenant Katte, planned a romantic escape to England, but their plot was discovered.The would-be escapees were arrested and condemned to death for desertion, and Katte was executed in Frederick's presence.  Frederick was imprisoned in the fortress of Küstrin in the most rigorous conditions

**Comment by nini92828** [comment]
In 1733, at his father's insistence, he married Elisabeth Christine of Braunschweig, but his aversion to women was so pronounced that the marriage was, over the many years it lasted, never consummated

**Comment by nini92828** [comment]
https://rickydphillipsauthor.wordpress.com/2015/06/05/twelve-things-you-didnt-know-about-frederick-the-great/
