### ISSUE TITLE
find out about how many countries are participating in the 2006 FIFA,

### ISSUE THREAD

**Issue by Dabtion** [iteloo/bitesize-berlin#15]

**Comment by KyleUnicorn1207** [comment]
Africa:
   Qualified teams
Angola
Ghana
Ivory CoastIvory Coast
Togo
Tunisia

Asia:
   Qualified teams
Australia
Iran
Japan
Korea Republic
Saudi Arabia

Europe:
   Qualified teams
Croatia
Czech Republic
England
France
Germany
Italy
Netherlands
Poland
Portugal
Serbia and Montenegro
Spain
Sweden
Switzerland
Ukraine

North, Central America and Caribbean:
   Qualified teams
Costa Rica
Mexico
Trinidad and Tobago
USA

South America:
   Qualified teams
Argentina
Brazil
Ecuador
Paraguay

Oceania:
 
NONE QUALIFIED (Oh...man)

Link: http://www.fifa.com/worldcup/archive/germany2006/teams/index.html
