### ISSUE TITLE
Who was Carl Gotthard Langhans?

### ISSUE THREAD

**Issue by Ephemeral-Equilibrium** [iteloo/bitesize-berlin#19]
Find out what Carl Gotthard Langhans had to do with the gate. What inspired him, any inspirations taken from other buildings?

**Comment by Dabtion** [comment]
Carl Gotthard Langhans was a Prussian architect. King Frederick Williams II ordered him to build this monument to represent peace. It was inspired by the Greek Parthenon.

http://www.visual-arts-cork.com/architecture/carl-gotthard-langhans.htm

**Comment by effervescence18** [comment]
http://www.visual-arts-cork.com/architecture/carl-gotthard-langhans.htm
