### ISSUE TITLE
Find things you want to eat

### ISSUE THREAD

**Issue by nini92828** [iteloo/bitesize-berlin#2]
Include at least 2 (1 sweet + 1 savor)
1. links to the website
2. reasons you want to eat it (why it's special, historical background etc. 
doesn’t have to be kadewe, do German dish.

**Comment by KyleUnicorn1207** [comment]
Cake

**Comment by effervescence18** [comment]
baguette 🥖

**Comment by effervescence18** [comment]
**Savor**: _Currywurst_
(1) fried pork sausage (German: Bratwurst) typically cut into slices and seasoned with curry ketchup, a sauce based on spiced ketchup or tomato paste, itself topped with curry powder, or a ready-made ketchup seasoned with curry and other spices. The dish is often served with French fries.
**Sweet**: _Schnecken_
(1) Schnecken dough is made with sour cream, while rugelach is made with cream cheese.
(2) Schnecken are rolled into a cylinder and sliced, becoming a flat spiral, whereas rugelach are formed from individual triangles of dough and rolled into a croissant shape. 

**References**: 
https://www.telegraph.co.uk/travel/destinations/europe/germany/articles/germany-best-food-dishes-to-eat/
https://berlinfoodstories.com/2016/05/04/kadewe/
