### ISSUE TITLE
Who was King Frederick William II? What did he do? What is his history?

### ISSUE THREAD

**Issue by Ephemeral-Equilibrium** [iteloo/bitesize-berlin#20]
Find out what King Frederick William II had to do with the gate and why it was built.

**Comment by ThomasTseng2005** [comment]
Frederick William  II of Prussia built the new Brandenburg gate which represents peace. While ruling, Prussia was weakened. He tried to restore Protestantism and has passion for art. So he built many famous buildings including Brandenburg Gate.

**Comment by Dabtion** [comment]
https://en.wikipedia.org/wiki/Frederick_William_II_of_Prussia
