### ISSUE TITLE
introduce Jesse Owens, and how he surprised the Nazi party by beating the best Aryan runner

### ISSUE THREAD

**Issue by Dabtion** [iteloo/bitesize-berlin#21]

**Comment by KyleUnicorn1207** [comment]
Jesse Owens was an American track-and-field athlete who won four gold medals at the 1936 Berlin Olympic Games while Germany was ruled by the Nazis.

- athletic career began in high school when he won three track and field events at the 1933 National Interscholastic Championships. Two years later, while competing for Ohio State University, he equaled one world record and broke three others before qualifying and competing in the 1936 Olympics. 

- Well known for his feat in defeating Hitler's ideology of Aryan supremacy and caused quite an uproar when Hitler refused to shake his hand.

Links: 
https://www.biography.com/people/jesse-owens-9431142
https://en.wikipedia.org/wiki/Jesse_Owens
