### ISSUE TITLE
Spy Myths

### ISSUE THREAD

**Issue by KyleUnicorn1207** [iteloo/bitesize-berlin#4]
Find
1. spy myth (movie spies)
Ex: Spies drive fancy cars like 007

[I need 5 of these (Total)]

**Comment by nini92828** [comment]
All special agents have six-pack abs.
https://www.vanityfair.com/hollywood/2015/07/mission-impossible-movie-spy-myths

**Comment by KyleUnicorn1207** [comment]
jnjnjjolk

**Comment by effervescence18** [comment]
(1)Spies aren't only human, uses animals too. 
(2) Espionage has often helped to prevent or reduce tension. The cold war wasn't exacerbated by that.
(3) Spes betray their countries mostly for money (false)
(4) Spies aren't always good looking
(5) High-speed car chases occur not according to plan and should be abandoned.
