### ISSUE TITLE
Find out about how the old Dome looks like(Drawing)

### ISSUE THREAD

**Issue by ThomasTseng2005** [iteloo/bitesize-berlin#6]
Draw out a picture of it

**Comment by KyleUnicorn1207** [comment]
![Uploading Screen Shot 2018-03-21 at 11.40.46 AM.png…]()

**Comment by KyleUnicorn1207** [comment]
Here's a drawing
<img width="710" alt="screen shot 2018-03-21 at 11 40 46 am" src="https://user-images.githubusercontent.com/37429618/37693770-db614f06-2cfc-11e8-937a-c2e4126f1cd0.png">
