### ISSUE TITLE
Spy Weapons

### ISSUE THREAD

**Issue by KyleUnicorn1207** [iteloo/bitesize-berlin#7]
Find:
1. Spy Movie weapons
(Name, year made/used, and usage)
link website down below
(Also need 5 items)

**Comment by Dabtion** [comment]
1. Kingsman Pistol (TT-30) 
2. M4A1
3. AK47
4. Kingsman Umbrella (Used in the bar fight scene)
5. Kingsman Grenade (disguised as a cigarette lighter)

**Comment by Ephemeral-Equilibrium** [comment]
https://www.cheatsheet.com/culture/james-bond-clever-spy-weapons.html/?a=viewall

**Comment by Ephemeral-Equilibrium** [comment]
https://www.vanityfair.com/hollywood/2015/07/mission-impossible-movie-spy-myths
